# Generated by Django 4.1 on 2023-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
