# Generated by Django 4.1 on 2023-06-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='estimated_start_date',
        ),
    ]
