# Generated by Django 4.1 on 2023-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_issue_in_backlog_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estimated_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estimated_start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
