# Generated by Django 4.1 on 2023-06-03 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sprint_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='index',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estimated_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='project',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
