# Generated by Django 4.1 on 2023-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sprint_index_alter_issue_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estimated_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
