# Generated by Django 4.1 on 2023-05-27 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rules.contrib.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_permissiongroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissiongroup',
            old_name='users',
            new_name='members',
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group', to='main.project'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('accepted', models.BooleanField(editable=False, null=True)),
                ('rejected', models.BooleanField(editable=False, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('permission_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.permissiongroup')),
                ('sent_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
