# Generated by Django 4.1 on 2023-04-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_column_order_alter_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
