# Generated by Django 4.1 on 2023-05-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_users_permissiongroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='permission_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.permissiongroup'),
        ),
    ]
