# Generated by Django 4.1 on 2023-06-03 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sprint_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_sprint',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_project', to='main.sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
