# Generated by Django 4.1 on 2023-05-27 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_invite_permission_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='Invitation',
        ),
    ]
