# Generated by Django 4.1 on 2023-04-22 13:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_colorlabel_issue_color_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorlabel',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
