# Generated by Django 4.1 on 2023-05-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_invitation_sent_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='rejected',
        ),
    ]
